### ISSUE TITLE
Initial Protocol Overview

### ISSUE THREAD

**Issue by oskarth** [status-im/specs#11]
This should give an overview of the protocol stack. Design goals, roughly mention each layer, what this gives in terms of guarantees, as well as specific considerations when it comes to using the layers together.

Things like how we do transport should to the greatest extent possible be an implementation detail, and instead be explained in a different document.

See https://github.com/status-im/specs/blob/master/x4.md for current draft.

## Acceptance criteria

- [ ] One can judge whether this protocol meets their requirements (functional as well as security) and technical stack.
- [ ] It should provide an intuition how the protocol works as a whole.
- [ ] Layers should be described as orthogonal pieces and what interfaces (if any) are required between them.

In terms of who will judge, it'll be 2-3 main groups initially:
- [ ] Ourselves in protocol group
- [ ] Client implementers (Core, Embark and Nimbus people i.e. status-js and Stratus)
- [ ] Core dev calls participants

**Comment by adambabik** [comment]
I am not sure about these acceptance criteria because this is only an overview. For example:

> Someone can read this and implement a Status client (including links to other specs)

This is not true for the overview. Reading the overview might tell someone whether this protocol meets their requirements or fits into their stack.

I would change them to:
- [ ] One can judge whether this protocol meets their requirements (functional as well as security) and technical stack.
- [ ] It should provide an intuition how the protocol works as a whole.
- [ ] Layers should be described as orthogonal pieces and what interfaces (if any) are required between them.

**Comment by oskarth** [comment]
Fair, changed to your points. Thanks for suggesting specific alternatives :)
